//! Raw FFI bindings to [LMDB](https://www.symas.com/lmdb), compiled from the
//! vendored upstream sources in `lmdb/` (provenance in `lmdb/VENDORED.md`).
//!
//! The declarations in `bindings.rs` are generated by bindgen from
//! `lmdb/lmdb.h` and committed, so building this crate does not need libclang.
//! Enable the `bindgen` feature to regenerate them after updating the vendored
//! sources. For a safe API, use the `natdb` crate.

#![allow(non_camel_case_types, non_upper_case_globals)]

/// Unix permissions for creating files (`mdb_mode_t` in `lmdb.h`).
#[cfg(unix)]
pub type mdb_mode_t = ::libc::mode_t;
/// Dummy permissions type on Windows, where LMDB ignores the mode (`mdb_mode_t` in `lmdb.h`).
#[cfg(windows)]
pub type mdb_mode_t = ::libc::c_int;

/// An OS file handle: a file descriptor on Unix (`mdb_filehandle_t` in `lmdb.h`).
#[cfg(unix)]
pub type mdb_filehandle_t = ::libc::c_int;
/// An OS file handle: an opaque `HANDLE` on Windows (`mdb_filehandle_t` in `lmdb.h`).
#[cfg(windows)]
pub type mdb_filehandle_t = *mut ::libc::c_void;

include!("bindings.rs");
